name: answer changeman-bot automatically

on:
  issue_comment:
    types: [created]

jobs:
  commentCreated:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.4
        with:
          template: .github/templates/comment-template.md
          vars: |
            foo: this

      - name: Edit Comment
        if: ${{  github.event.comment.user.login == 'VitorinoAssuncao' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.comment.id }}
          body: ${{ steps.template.outputs.result }}
          edit-mode: replace
