name: answer changeman-bot automatically

on:
  issue_comment:
    types: [created]

jobs:
  commentCreated:
    if: github.event.issue.pull_request != null
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get PR number
        run: echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV

      - name: Get PR description using API.
        run: |
          DESCRIPTION=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ env.PR_NUMBER }}" | jq -r '.body')
          
          # Extrai o trecho entre "Descrição" e "Evidências"
          EXTRACTED_DESCRIPTION=$(echo "$DESCRIPTION" | awk '/Descrição/{flag=1; next} /Evidências/{flag=0} flag')
          
          # Verifica se foi extraído algo, se não, define um fallback
          if [[ -z "$EXTRACTED_DESCRIPTION" ]]; then
            EXTRACTED_DESCRIPTION="N/A"
          fi
          
          # Converte quebras de linha em literais "\n"
          EXTRACTED_DESCRIPTION=$(echo "$EXTRACTED_DESCRIPTION" | awk '{printf "%s\\n", $0}')
          
          # Escapa aspas duplas
          EXTRACTED_DESCRIPTION=$(echo "$EXTRACTED_DESCRIPTION" | sed 's/"/\\"/g')
          
          echo "EXTRACTED_DESCRIPTION=$EXTRACTED_DESCRIPTION" >> $GITHUB_ENV

      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.4
        with:
          template: .github/answer-changebot-template.md
          vars: |
            description: "${{ env.EXTRACTED_DESCRIPTION }}"

      - name: Edit Comment
        if: ${{ github.event.comment.user.login == 'VitorinoAssuncao' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.comment.id }}
          body: ${{ steps.template.outputs.result }}
          edit-mode: replace
