name: Update PR Values

on:
  pull_request:
    types: [opened, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  label-and-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR Author
        uses: toshimaru/auto-author-assign@v2.1.1

      - name: Label PR Based on Title (enhancement)
        uses: fregante/title-to-labels-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keywords: |
            feat
            feature
            enhancement
          labels: |
            enhancement

      - name: Label PR Based on Title (bug)
        uses: fregante/title-to-labels-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keywords: |
            bug
          labels: |
            bug

      - name: Label PR Based on Title (doc)
        uses: fregante/title-to-labels-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keywords: |
            doc
            documentation
          labels: |
            doc