name: answer changeman-bot automatically

on:
  issue_comment:
    types: [created]

jobs:
  commentCreated:
    runs-on: ubuntu-latest
    steps:
      - name: Render template
        id: template
#        uses: chuhlomin/render-template@v1.4
#        with:
#          template: ./answer.template.md
        run: echo ${{ ls }}

      - name: Edit Comment
        if: ${{  github.event.comment.user.login == 'VitorinoAssuncao' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.comment.id }}
          body: ${{ steps.template.outputs.result }}
          edit-mode: replace
