name: answer changeman-bot automatically

on:
  issue_comment:
    types: [created]

jobs:
  commentCreated:
    runs-on: ubuntu-latest
    steps:
      - name: Edit Comment
        if: ${{  github.event.comment.user.login == 'VitorinoAssuncao' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.comment.id }}
          body-path: 'workflows/templates/auto_answer_changeman.md'
          edit-mode: replace
