name: answer changeman-bot automatically

on:
  issue_comment:
    types: [created]

  workflow_dispatch:

jobs:
  edit-pr-comment:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != ''
    steps:
      - name: Debug
        run: echo "Outro"
