name: answer changeman-bot automatically

on:
  issue_comment:
    types: [created]

jobs:
  commentCreated:
    if: github.event.issue.pull_request != null
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get PR number
        run: echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV

      - name: Get PR description using API
        run: |
          DESCRIPTION=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ env.PR_NUMBER }}" | jq -r '.body')
          
          echo "Full PR Description:"
          echo "$DESCRIPTION"

          # Extrai apenas a seção "Descrição"
          EXTRACTED_DESCRIPTION=$(echo "$DESCRIPTION" | awk '/## :cyclone: Descrição/{flag=1; next} /## :mag_right: Evidências/{flag=0} flag')

          echo "Extracted PR Description: $EXTRACTED_DESCRIPTION"

          # Passa o valor como variável do GitHub Actions
          echo "EXTRACTED_DESCRIPTION=$EXTRACTED_DESCRIPTION" >> $GITHUB_ENV

      - name: Use the extracted description field
        run: |
          echo "The extracted description is: ${{ env.FIELD_VALUE }}"

#      - name: Render template
#        id: template
#        uses: chuhlomin/render-template@v1.4
#        with:
#          template: .github/answer-changebot-template.md
#          vars: |
#            foo: this
#
#      - name: Edit Comment
#        if: ${{  github.event.comment.user.login == 'VitorinoAssuncao' }}
#        uses: peter-evans/create-or-update-comment@v4
#        with:
#          comment-id: ${{ github.event.comment.id }}
#          body: ${{ steps.template.outputs.result }}
#          edit-mode: replace
