name: answer changeman-bot automatically

on:
  issue_comment:
    types: [created]

jobs:
  commentCreated:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
#        uses: peter-evans/create-or-update-comment@v4
#        with:
#          comment-id: ${{ github.event.comment.id }}
#          reactions: eyes
        run: echo "${{ github.event.comment.id }} \n ${{ github.event.comment.user.login }}"