name: answer changeman-bot automatically

on:
  issue_comment:
    types: [created]

jobs:
  commentCreated:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v4
        if: ${{github.event.comment.user == 'VitorinoAssuncao'}}
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: eyes
