---
name: Quality On Deploy

on:
  deployment

permissions:
  contents: write
  pull-requests: write

env:
  THRESHOLD-FILE: 0
  THRESHOLD-PACKAGE: 0
  THRESHOLD-TOTAL: 10

jobs:
  run-coverage:
    name: Run Coverage and update badges on Deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature: ['pkgs']
    continue-on-error: true
    steps:
      - name: Checkout
        if: steps.skip.outputs.should_skip != 'true'
        uses: actions/checkout@v4

      - name: Set up Go
        if: steps.skip.outputs.should_skip != 'true'
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version: '1.24.2'

      - name: Run make coverage
        id: coverage
        run: |
          cd ${{ matrix.feature }}
          make coverage
          echo "total=$(tail -n 1 coverage.total)" >> $GITHUB_OUTPUT
          cd ..

      - name: Run go-test-coverage
        id: test-coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: ${{ matrix.feature }}/coverage.out
          threshold-file: ${{ env.THRESHOLD-FILE }}
          threshold-package: ${{ env.THRESHOLD-PACKAGE }}
          threshold-total: ${{ env.THRESHOLD-TOTAL }}
          badge-file-name: ${{ matrix.feature }}-deploy-coverage.svg
        continue-on-error: true

      - name: Check Badge Value
        run: |
          cat ${{ matrix.feature }}-deploy-coverage.svg

      - name: Upload Badge
        id: upload-badge
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.feature }}-deploy-coverage
          path: ${{ matrix.feature }}-deploy-coverage.svg
          if-no-files-found: error

      - name: Checkout badge Branch
        uses: actions/checkout@v4
        with:
          ref: badge

      - name: download badge
        id: download-badge
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.feature }}-deploy-coverage.svg

      - name: Update coverage badge
        run: |
          cat ${{ matrix.feature }}-deploy-coverage.svg
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ${{ matrix.feature }}-deploy-coverage.svg
          git commit -m "update coverage on deploy badge" || true
          git push origin badge
